print("This program is work swapping")
a=int(input("enter first number"))
b=int(input("enter sceond number"))
print("After swapping a" ,a)
print("After swapping b",b)
print("After swapping a",b)
print("After swapping b",a)